# 跑不起来
version: "3"
services:
  python:
    image: python
    restart: always
    #ports:
    #  - 8081:8081
    container_name: server-python-172.4.0.60
    volumes:
     - .:/opt/python
    command: python /opt/python/spider_app.py
    networks:
      default:
        ipv4_address: 172.4.0.60
networks:
  default:
    external:
      name: 2019_nCoV_network
